### PR TITLE
Allow for set and other unsubscriptable data structures.

### PR DESCRIPTION
**Pull request by craiga**
An attempt to fix https://github.com/pyexcel/pyexcel-xlsx/issues/52

With your PR, here is a check list:

- [x] Has test cases written?
- [x] Has all code lines tested?
- [x] Has `make format` been run?
- [x] Please update CHANGELOG.yml(not CHANGELOG.rst)
- [x] Has fair amount of documentation if your change is complex
- [x] Agree on NEW BSD License for your contribution

### CODE REVIEW

**Comment by craiga** [comment]
Some tests are still failing here on my machine and I'm not sure whether this is due to my environment, whether my change has has an unintended consequence, or whether an update to some other library is causing an issue in the tests.

**Review by kodurusivakumar34 — APPROVED** [review]

**Comment by kodurusivakumar34** [comment]
can you someone try to merge this fix?

**Comment by kodurusivakumar34** [comment]
@craiga can you please try to merge this pull request

**Comment by craiga** [comment]
@kodurusivakumar34 I don't have write permissions here, that'd be a job for @chfw I believe.

**Comment by kodurusivakumar34** [comment]
@chfw can you please review and merge this PR

**Comment by Mokatsu** [comment]
What's the status on this merge?

**Review by kzadm — APPROVED** [review]

**Pull request merged**
